use_frameworks!

platform :ios, '8.0'

target 'MJProgressHUD_Example' do
  pod 'MJProgressHUD', :path => '../'

  target 'MJProgressHUD_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
